- .github/workflows/deploy.yaml
- infrastructure/README.md
to streamline the process a bit. Maybe we can do the same with plain env vars but `env` contains user-provided as well as GH specific env vars.
> pass all GH secrets to helm

- app/controllers/suppliers_controller.rb
Adds meta descriptions, as defined in the content design google docs for the [main table page](https://docs.google.com/document/d/1iArgov3r8PZA8uxH_7oLO_b8a5scUUoUUNgqD23pYDw/edit) and [supplier detail page](https://docs.google.com/document/d/1ifMho6ovQlzQloFhEQhjMRwLcMsNTRUJwB7_4iVkxFA/edit).
Main table page meta description:
> Don’t switch before you compare customer services. Large energy companies ranked by number of complaints, wait times and commitments. Check your supplier.
Supplier detail page meta description:
> Customer service contact details and scores for _supplier_name_. Find out how well _supplier_name_ customer service performs and how to contact them.
> feat: add meta descriptions

- app/controllers/suppliers_controller.rb
The Data team use page GUID to report on page views for advice content. Currently pages in the energy CSR table don’t have page GUIDs, so we need to add them.
In `public-website` we use either the Episerver ID or Contentful ID as `GUID`. However, since the pages for the Energy CSR table don't exist as such in Contentful I have instead used:
- `energy-csr-table` as the `GUID` for the main comparison table page
- `energy-csr-#{slug}` as the `GUID` for the individual supplier detail pages.
`slug` is a unique field for the `energySupplier` content type in Contentful.
> Add page GUID to pages

- infrastructure/app/stages/dev.yaml
Currently both the prod and qa environments use production data.
This PR adds the `USE_TEST_SUPPLIERS` environment variable to the deployment pipeline, so that qa can use test data instead.
> Use test data in qa environment

- app/components/score_summary_component.html.haml
- app/helpers/content_helper.rb
- app/views/suppliers/index.html.haml
- spec/components/score_summary_component_spec.rb
Updates dates on the app to reflect new quarter data for October to December 2023, and next publishing date of June 2024.
Note: do not merge in until the date that the next quarter's data is published. This is anticipated to be 26th March, but not yet confirmed.
> feat: update quarter dates March 2024

- .github/workflows/deploy.yaml
- .github/workflows/lint_and_test.yml
- .github/workflows/review-app-create.yml
- .github/workflows/review-app-destroy.yml
These actions were using Node.js 16, which is deprecated. The latest versions use Node.js 20.
> Upgrade node-based GitHub Actions to latest versions

- .github/workflows/review-app-scan.yml
This uses a patched version of the review app scan script that will prevent workflow errors when the list of namespaces is empty.
> Use patched review app scan script to prevent errors when array is empty

- infrastructure/app/stages/prod.yaml
Adds feature flag to env vars list for GH actions. Have also added an env var to the prod environment of the repo within GH settings.
> Add quarter dates feature flag as environment variable for production

- Gemfile.lock
Manually upgraded `rack` to 3.1.6, as dependabot couldn't create a PR to address the security vulnerability.
> Upgrade rack to address security vulnerability

- app/views/suppliers/index.html.haml
- app/views/suppliers/show.html.haml
- infrastructure/app/stages/dev.yaml
- infrastructure/app/stages/prod.yaml
Always serve quarter dates from Contentful.
> chore: remove feature flag FF_CONTENTFUL_QTR_DATES

- .github/resources/preview-overrides.yaml
Review apps currently use secrets defined in github dev environment, but not the environment variables defined there. This PR brings parity of approach.
See the [review app created by #348](https://review-348-energy-comparison-table.qa.citizensadvice.org.uk/) for comparison. That review app uses the live supplier data, whereas this one uses test supplier data.
> feat: set review apps to use dev env vars

- Gemfile.lock
Bumps rexml to 3.3.2 to address moderate security vulnerability CVE-2024-39908. Dependabot was unable to raise the PR for this.
> chore: bump rexml version to fix Dependabot alert

- infrastructure/app/stages/prod.yaml
Have also set the env var of FF_SMALL_SUPPLIER_STARS in the production github environment.
> feat: turn on small supplier stars feature in production

- README.md
The main repo documentation didn't previously refer to environment variables or secrets, but they were mentioned within the infrastructure README. This PR adds a link to Configuration section of the infrastructure README to the main repo README, so that environment variable information can be found easily.
> Make environment variables info easier to find

- .github/workflows/deploy.yaml
- infrastructure/app/chart/energy-comparison-table/values.yaml
Uses [citizensadvice/message-slack-action@v1](https://github.com/citizensadvice/message-slack-action) to post build notifications to slack re deployment success or failure. Code cribbed from [casebook PR](https://github.com/citizensadvice/Casebook/pull/8974).
> Chore: post build notifications to slack

- .github/dependabot.yml
Removes minor version updates to `rails` from dependabot updates, so that we can manage them intentionally.
> Chore: set dependabot to ignore minor version updates for rails

- app/views/suppliers/index.html.haml
Adds a fragment id to both the small suppliers form and to the action of the form, so that when the user chooses a small supplier they are taken to the small supplier details and not sent back to the top of the page.
> fix: move straight to small supplier details when one has been selected

- .github/workflows/deploy-energy-apps.yaml
Adds `prod` back into the deployment GHA workflow, so the app is also deployed to the new prod environment.
Protection rules prevent this workflow deploying into prod from a branch (https://github.com/citizensadvice/energy-comparison-table/actions/runs/11495591764/job/31995501661)
> feat: add prod back into matrix

- .github/workflows/upload-js-to-datadog.yml
- infrastructure/app/chart/energy-apps/templates/deployment.yaml
- infrastructure/app/chart/energy-apps/values.yaml
Follows on from https://github.com/citizensadvice/energy-apps/pull/483
Fixes the `APP_VERSION` env var so that it is:
- set directly in the `deployment.yaml` file
- more explicitly linked to the `IMAGE_TAG` used in the docker build and push step
> feat: use image tag for app version

- .github/workflows/deploy-energy-apps.yaml
- app/javascript/application.js
Re-enables prod deployments and removes the deliberate JS error now that the datadog JS error logging is working.
> feat: turn on prod deployments and remove js error

- infrastructure/app/chart/energy-apps/templates/deployment.yaml
Kubernetes calls the /status endpoint every few seconds on every pod to check that the application is up and running. There is normally no need to send these logs to Datadog. Removing them will reduce our Datadog costs.
We already exclude these logs for public-website and content-api, and it's never caused a problem.
> Exclude /status requests from Datadog logs

- app/controllers/queries/appliances.rb
- spec/cassettes/appliance/fetch_all_production.yml
- spec/cassettes/appliance/fetch_all_test.yml
- spec/cassettes/daily_usage_creation/steps/appliance.yml
- spec/models/appliance_spec.rb
We were only fetching the metadata to test it in rspecs, it is not used by the app anywhere.  This change removes the tags info from the query but still tests that appliances are returned when test and production appliances are requested.
> fix: stop fetching contentful metadata tags in appliance calculator

- app/controllers/appliance_calculator/application_controller.rb
Ensures that the `no-js` parameter is preserved when requesting the no js version of the app from public website
Prior to this change, the param was getting lost in the redirect to the first step of the form.
> fix: preserve no-js param on redirect

- app/javascript/appliance-calculator.js
- app/javascript/modules/resize-iframe.js
In certain circumstances, the height of the iframe is 1 pixel short (?pixel rounding).  This causes conflicting scrolling issues when the app is iframed into an advice collection page on the main site.  This change adds a safety margin of 5px to the height sent to the parent window in `postMessage`, as well as refactoring the resizing javascript into a module so it is consistent with everything else.
> fix: height rounding causes scroll issue when the app is in a iframe

- config/application.rb
We want to use the `X-Forwarded-Host` header for these app now, since the appliance calculator has form POSTs, cookies and redirects.
[The change in public-website-config](https://github.com/citizensadvice/public-website-config/pull/1370) has been deployed to `okapi` ([see the example here](https://cdn.okapi.content.citizensadvice.org.uk/consumer/energy/energy-supply/interactive-tool-test/)), but we currently get a `403` error because `cdn.okapi.content.citizensadvice.org` doesn't match the allowed hosts in `config.hosts`.
> fix: allow all CA subdomains only

- config/initializers/session_store.rb
Makes the cookie name for the energy apps more specific so we can tell what it is out in the wild.
> feat: make cookie name specific

- app/assets/stylesheets/appliance-calculator.scss
- app/assets/stylesheets/appliance-calculator/_form_actions.scss
- app/components/appliance_calculator/clear_list_component.html.haml
- app/components/appliance_calculator/clear_list_component.rb
- app/views/appliance_calculator/daily_usage_creation/steps/_form.html.haml
- app/views/appliance_calculator/daily_usage_creation/steps/completed.html.haml
- features/appliance_calculator/clear_list.feature
- features/step_definitions/appliance_calculator/appliance_calculator_steps.rb
When the user has added an appliance, we want to show the `Clear list` button on every step, not just on the completed screen.
> Show 'Clear list' button on all steps

- app/helpers/footer_helper.rb
CAS have restructured cas.org.uk, and the old links were broken.
Also update some of the other Scotland footer links to be consistent with public-website.
> Fix links in Scotland footer

- infrastructure/app/chart/energy-apps/templates/poddisruptionbudget.yaml
The PDB refers to a missing environment value in `.Values.metadata`.  We do not use this anywhere else so it is fine to delete it
> fix: remove metadata.environment from PDB config

- Dockerfile
Moves the docker build to a multi stage build, removing build tools from the final deployed image.  Same as the changes made to the smart meter tool in https://github.com/citizensadvice/smart-meter-tool/pull/528
> feat: move to multistage build

- infrastructure/app/chart/energy-apps/templates/deployment.yaml
There is a documented race condition between kubernetes removing a pod and puma stopping (see https://github.com/puma/puma/blob/master/docs/kubernetes.md).
> feat: add a prestop hook to avoid race conditions

- .trivyignore
To ignore vulnerability warning for a vulnerability that doesn't affect us because we don't use net-imap.
> chore: add net-imap CVE to .trivyignore

- infrastructure/app/chart/energy-apps/templates/probe.yaml
- infrastructure/app/chart/energy-apps/templates/web_probe.yaml
- infrastructure/app/chart/energy-apps/values.yaml
- infrastructure/app/stages/dev.yaml
- infrastructure/app/stages/prod.yaml
Follows [SRE documentation on adding a probe to monitor website availability](https://citizensadvice.atlassian.net/wiki/spaces/OPS/pages/4471653100/Kubernetes+add+a+Probe+to+monitor+website+availability). [Jira ticket CP-748](https://citizensadvice.atlassian.net/browse/CP-748). 
Testing the uptime monitoring with `energy-apps`, with a view to adding to other Content Platform apps.
> chore: add uptime monitoring

- infrastructure/app/stages/dev.yaml
Scheduling was set to take the dev app down overnight and at weekends, but this isn't compatible with uptime monitoring that we've added for the dev environment.
> Remove zalando schedule actions

- infrastructure/app/chart/energy-apps/values.yaml
- infrastructure/app/stages/dev.yaml
- infrastructure/app/stages/prod.yaml
Increases `minReplicas` to 2 for `dev` to match `prod`, and adds a PDB to `dev`. 
This is to stop dev being unavailable when the node is rotated due to underutilization. The pods being killed was resulting in the dev app being unavailable and alerts posting in [#content-platform_develop_kube_alerts](https://acab.slack.com/archives/C05ABFT5NTG).
> Increase min replicas add PDB to dev

- .github/workflows/deploy-energy-apps.yaml
- .github/workflows/review-app-create.yml
Reverts citizensadvice/energy-apps#558
`build` job of `deploy-energy-apps` workflow can't find Dockerfile. Can't immediately see why that should be the case, so reverting for now.
Note that `build` is currently using `citizensadvice/build-and-private-ecr-push-action`, which is described as being for private repos only. The README for `citizensadvice/build-and-push-action` also confusingly identifies itself as being for private repos, despite being linked to from `citizensadvice/build-and-private-ecr-push-action` as the option for public repos. I've [asked SRE to confirm whether we should be using citizensadvice/build-and-push-action instead](https://acab.slack.com/archives/C061NCX5SM8/p1752224685613389).
> Revert "[dependabot:actions] bump citizensadvice/build-and-private-ecr-push-action from 1 to 3"

- .github/workflows/deploy-energy-apps.yaml
- .github/workflows/review-app-create.yml
Should allow v3 of citizensadvice/build-and-private-ecr-push-action to be able to build the image successfully. Without the actions checkout step the build image job was failing to find Dockerfile
> fix: add actions checkout step to build image jobs

- .github/workflows/deploy-energy-apps.yaml
- .github/workflows/review-app-create.yml
Upgrade citizensadvice/build-and-private-ecr-push-action to version 3
> chore: upgrade to version 3

- .github/resources/preview-overrides.yaml
Prometheus probes have been enabled within energy apps, but the review apps setup wasn't included in the update at the time so deployed a review app causes alerts to fire.  The url isn't static as it's generated based off of the PR number, and as they're short lived deployments, we are going to disable the probes for them
> Disable prometheus probe for review apps

- .github/workflows/lint_and_test.yml
- config/environments/test.rb
- features/cookie_preferences.feature
- features/step_definitions/cookie_preferences_steps.rb
- features/support/env.rb
Adding a feature test to check that the cookie banner is rendered when the user first visits a page.
We had to add additional Capybara configuration - the default browser the app uses for running the feature tests is `rack_test` which doesn't run javascript. We've added `@javascript` tag only to the cookie preferences tag and adjusted it to use `selenium_chrome_headless`.
> Cp 873 add feature tests in energy apps for the cookies

- config/application.rb
Rate changed to 26.35p with effect from 1st October 2025. See Jira ticket [CP-932](https://citizensadvice.atlassian.net/browse/CP-932).
[CP-932]: https://citizensadvice.atlassian.net/browse/CP-932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-932 update default electricity unit rate
